### ISSUE TITLE
The spacing of text in annotations is off in print design

### ISSUE THREAD

**Issue by palewire** [datadesk/datawrapper-migration#33]
Currently the default size for annotations on export is too large.

![Screenshot from 2019-11-01 09-10-10](https://user-images.githubusercontent.com/9993/68038534-6b26cc00-fc87-11e9-901c-5e21f243f1e0.png)

[Annotaton-labels-in.print.design.pdf](https://github.com/datadesk/datawrapper-migration/files/3798640/Annotaton-labels-in.print.design.pdf)

**Comment by elanals** [comment]
This issue is a little bit tricky, the trouble is that currently selected theme defines:
- The default size of an annotation, **when you add it**
- The unit used for the annotations (px/pt)

The trouble is that in the current configuration, if you add annotations whilst working in the web layout, they will be set to 14 (which is taken as px, because it's a web theme), when you switch to the print layout, the existing annotations will still be set at 14 (except in pt). This is however naturally much too large and not in keeping with your defaults. The size can be changed for the individual annotations via the UI, but this is naturally extra work, so not ideal. I had already configured your print theme to ensure that any annotations **created** whilst working in the print mode would have the 8pt default, but that solution doesn't help if you create the chart in the web mode first, and I understand wouldn't be ideal to have to create the annotations twice.

Whilst it's not currently possible to dynamically change the settings for those annotations when you switch themes, one solution I could offer would be to to **hard code the font sizes** for the two layouts. This means that the sizes would always be in keeping with the styleguide, but that changing the font size with the UI would have no effect. Do you think this would be a reasonable solution?

**Comment by palewire** [comment]
Yes. I think hard coding them in could work. In my opinion, this is one of those cases where we will benefit from limiting what users can do.

**Comment by elanals** [comment]
This has been done for a while, forgot to comment.
