### ISSUE TITLE
Switching from web design to print design on existing chart doesn't stick on PDF export

### ISSUE THREAD

**Issue by palewire** [datadesk/datawrapper-migration#34]
Watch video here to see the bug https://imgur.com/hEmjUDT

**Comment by elanals** [comment]
I think I know what's happening here, would probably help to clarify how the web/print switch works:

- When you create a new chart, it will automatically have the web theme
- And you will also automatically be in the **Web** mode 
![image](https://user-images.githubusercontent.com/19191012/68212538-03031d80-ffda-11e9-8536-ef421abe940e.png)

- During the chart editing process, the moment you switch over to the **Print** mode for the first time, you create a 'fork' of the same chart, from now on, any settings you apply in **Print** mode, will only be applied to the print version, and any settings you apply in **Web** mode will only be applied in the web version.
- The first time you make the switch from web to print, Datawrapper automatically switches the layout to the print layout
- If however, whilst working in **print** mode, you manually change the layout to the web layout in the **Design** tab, from the **Select layout** dropdown, **this setting will also be saved to the print version**
- when you proceed to the publish step, initially the **web version** that you created is shown, with all the settings that were applied whilst working in **Web** mode
- when you hit the PDF Export button, the preview changes to the **print version**, corresponding to all the settings that were applied whilst working in the **Print** mode.

See this demonstrated on a newly created chart:
![web-print](https://user-images.githubusercontent.com/19191012/68212856-ae13d700-ffda-11e9-8174-36851fe2f6f2.gif)

And see what happens when I manually change the layout whilst working in print mode:

![web-print2](https://user-images.githubusercontent.com/19191012/68213116-3e521c00-ffdb-11e9-9785-6dfab4cb4a59.gif)

To resolve this issue for this particular case, simply go back to the **Visualize** step, switch to **print** mode, and select the LA Times (print) layout from the **Design tab,** then this layout will again be applied to the print version of the chart

In general, to avoid this happening in future, the recommended workflow would be to just let the web/print switch take care of the applying the correct theme, and to avoid making an active selection in the **Design** tab. Does this make sense?

**Comment by palewire** [comment]
Thank you for this explanation. In response I am going to file a new ticket that I think can help prevent user confusion.
