### ISSUE TITLE
Text annotation not appearing, or appearing in the wrong place, in iframe

### ISSUE THREAD

**Issue by palewire** [datadesk/datawrapper-migration#35]
[Here's what happens](https://imgur.com/6HzR8Ga) on datawrapper, where you can see the annotation disappear or clipped or something on the iframe URL

But then different behavior on our live site when embedded.

![Screenshot from 2019-11-04 15-54-19](https://user-images.githubusercontent.com/9993/68167859-df799d80-ff1b-11e9-9c1e-033590d7adaf.png)

Here's the URL to this chart. We've been monkeying with the custom scale and annotation settings so not everything is identical to when we took the video and image above. https://app.datawrapper.de/chart/WgFHg/publish

**Comment by elanals** [comment]
So the behaviour of the annotation at different widths will depend on the way it was positioned, defined by a few factors:

1. The x,y coordinates of where it was placed, shown in these two input fields. This is **relative to the chart scale**, and will change in proportionally as that changes at different widths/heights, this allows you to anchor annotations to particular chart features, and ensure they stay at that position relative to them, even when resizing 

![image](https://user-images.githubusercontent.com/19191012/68215283-40b67500-ffdf-11e9-88dc-df474d84d379.png)

2. The offset. Defined on an absolute scale, in pixels, and is used to fine-tune the position, or ensure the position relative to any other nearby annotations is exact and consistent, even at different widths

![image](https://user-images.githubusercontent.com/19191012/68215842-35b01480-ffe0-11e9-8b99-da6139fbe9ef.png)

3. The anchor point

![image](https://user-images.githubusercontent.com/19191012/68215532-b3275500-ffdf-11e9-8282-acfb90fdea07.png)

The trouble here is that you're looking to anchor the annotation relative to the **frame bounds**, as opposed to the chart scale, which is not what annotations are optimized for, and why you run into troubles when the width is changed. This can be made somewhat better by ensuring that you set the anchor point as the bottom left corner, define the x,y position at the beginning of the x-scale, and make use of the offset to get the position right, but it's still not perfect, due to scale changes on resizing, the annotation will still shift a bit as the scale changes:

![Annotation trouble](https://user-images.githubusercontent.com/19191012/68216079-9d665f80-ffe0-11e9-9e2b-884ad673aa2a.gif)

In this case I would actually suggest an alternative solution, you could put the unit text in the description, like this:

![image](https://user-images.githubusercontent.com/19191012/68216214-da325680-ffe0-11e9-9912-2c33c6c2a50c.png)

![image](https://user-images.githubusercontent.com/19191012/68216264-ecac9000-ffe0-11e9-84f1-15c0f6a2e0b2.png)

And if you want to avoid using html in the header, and think this could be a feature you would use often, we could add an additional field for you in the **Annotate** section, where you can input text that will automatically be shown below the description like this, let me know if you'd be interested in having something like that set up

**Comment by palewire** [comment]
Thank you for the detailed response. I believe I understand the situation now.

At the end of your message, you suggested

> And if you want to avoid using html in the header, and think this could be a feature you would use often, we could add an additional field for you in the Annotate section, where you can input text that will automatically be shown below the description like this, let me know if you'd be interested in having something like that set up

I am confident this is a feature we would use frequently. And I'm confident that others newsroom users would as well. In many newsroom that position is the common home for y-axis labels. If you're able to add that feature as proposed, we would welcome it.

**Comment by elanals** [comment]
@palewire we can certainly do this, in fact I already have. The only situation where I imagine this wouldn't quite do the trick of playing an axis label is if you also have a legend, which would come between the label and the chart itself. You should find that you now have a section in the Annotate tab called **custom fields** and in there a field called **Unit label** (you can rename this on the team settings page). Text you put in there will get added to the bottom of the header in bold.

**Comment by palewire** [comment]
Thank you.
