### ISSUE TITLE
Hide "social sharing" button

### ISSUE THREAD

**Issue by palewire** [datadesk/datawrapper-migration#44]
We don't want our users clicking the social sharing option on the design tab. Some do it anyway. We request that you either:

- [ ] Hide the button permanently for our account
- [ ] Add a settings option to hide it from users, like you can hide chart types.

**Comment by elanals** [comment]
Unfortunately, it's not currently possible to opt out of individual settings at the moment, though this is something we're looking to add in future. What I can do however would be to force hide the buttons themselves, so that even if a user did turn the option on, it would have no effect (UI-wise not ideal, but presumably better than unwanted share buttons)

**Comment by palewire** [comment]
If hiding the checkbox isn't possible then, yes, I'd like you to remove the share buttons from our theme.

**Comment by elanals** [comment]
Done

**Comment by palewire** [comment]
Thank you.
