### ISSUE TITLE
Add more notes fields for charts and maps

### ISSUE THREAD

**Issue by LElebee** [datadesk/datawrapper-migration#47]
https://app.datawrapper.de/table/WIV85/visualize#annotate

When there are multiple notes, they string together in Datawrapper. Allow returns to separate different notes or add + more note fields.
Attached is a sample of how they currently show in Datawrapper.
In this case, each asterisk'd note needs to go in a separate line. 
![multiple notes to separate](https://user-images.githubusercontent.com/17730643/69471749-c2383200-0d57-11ea-9b23-8ea89db946f4.jpg)

**Comment by elanals** [comment]
You can train users to use a <br> tag which will force a line break. From an implementation perspective I don't think I could guarantee us adding a dynamic "+add note" functionality particularly quickly due to the fact that we've got a lot going on and the usage of <br> is fairly standard for when you need new lines, so I would definitely recommend doing that for the time being.

I do think in general for these types of text fields it would definitely make sense for us to move in a 'what you see is what you get' direction that would mean that the user could just press enter for a new line, instead of having to be confronted with html tags, and I'll definitely suggest this internally

**Comment by elanals** [comment]
You can train users to use a <br> tag which will force a line break. From an implementation perspective I don't think I could guarantee us adding a dynamic "+add note" functionality particularly quickly due to the fact that we've got a lot going on and the usage of <br> is fairly standard for when you need new lines, so I would definitely recommend doing that for the time being.

I do think in general for these types of text fields it would definitely make sense for us to move in a 'what you see is what you get' direction that would mean that the user could just press enter for a new line, instead of having to be confronted with html tags, and I'll definitely suggest this internally

**Comment by palewire** [comment]
I agree that a WSIWYG editor where newlines int he text translated to <br> tags in the HTML would be great.

**Comment by LElebee** [comment]
yes, thanks.
