### ISSUE TITLE
Add 0 tick label on y-axis of column and line charts

### ISSUE THREAD

**Issue by palewire** [datadesk/datawrapper-migration#5]

**Comment by elanals** [comment]
For column charts it was the case that the 0 tick label wasn't shown, this has been adjusted for your layout so that it now gets shown. For line charts however the zero getting shown is the default behaviour, so if you're noticing examples where that isn't the case, please link them here so we can take a look!

**Comment by palewire** [comment]
I am still not seeing the zero [here](https://app.datawrapper.de/chart/ZPEJf/visualize#annotate)

**Comment by elanals** [comment]
Sorry, my mistake. Should be resolved now.
