### ISSUE TITLE
Align print and web color palettes so web to print conversions don't cause problems

### ISSUE THREAD

**Issue by palewire** [datadesk/datawrapper-migration#63]
In response to bug report #57, @elanals proposed the resyncing of our print and web palettes, at least for the first X number of colors as a solution to the bug.

If it is possible, I think we should pursue this route to kill the bugs once and for all. Though I worry that we are failing to properly communicate these color changes via GitHub and propose that we schedule a phone call for the week after Christmas to iron out all the wrinkles.

**Comment by elanals** [comment]
Please let me know once you have a finalised color palette here so that i can implement that for both print and web!

**Comment by LElebee** [comment]
Hi @elanals here is a pdf with our standard colors we would like to have. Is it possible to add breaks in between these color groupings? And thank you Elana!
[LAT_standard_colors.pdf](https://github.com/datadesk/datawrapper-migration/files/4055570/LAT_standard_colors.pdf)

**Comment by elanals** [comment]
Hi @LElebee thanks for the pdf! I just set that up. We don't have the option to add color groupings in the color picker just yet though it's in the pipeline. 

If you want for the time being I could add some extra white swatches so that the line breaks happen at the correct places. Could look something like this:

![image](https://user-images.githubusercontent.com/19191012/72342730-78235b00-36cd-11ea-988f-c3fc23170a12.png)

(The swatches there have to be made pretty small to fit 9 in, if you think different line breaks would make more sense let me know) otherwise we can also just wait until the official color grouping feature is launched.

**Comment by LElebee** [comment]
Hi Elana, yes! white swatches to separate the color groups is a good idea for now. Thank you!

Lorena
________________________________

**Comment by elanals** [comment]
Ok I implemented as above, I hope the swatches aren't too small now though!
