### ISSUE TITLE
$ prefix not appearing in y-axis of print line charts

### ISSUE THREAD

**Issue by palewire** [datadesk/datawrapper-migration#65]
In [this example](https://app.datawrapper.de/chart/5vr80/) you can see that a `$` prefix has been prepended to our data column, yet it does not does appear in the print preview of the chart. Our preference would be for the $ to appear just once, after the first, or top, value in the y-axis labels. 

![Screenshot from 2020-01-02 14-03-50](https://user-images.githubusercontent.com/9993/71696111-f34d4e80-2d68-11ea-89da-9cb7293ddad2.png)

![Screenshot from 2020-01-02 14-03-34](https://user-images.githubusercontent.com/9993/71696116-f6483f00-2d68-11ea-8032-d7eb41bacbf8.png)

**Comment by elanals** [comment]
This was an issue to do with the web/print switch, looks like the $ was applied after the chart had been forked into the print/web versions, which is why it was only applied to the web version. As there's no web/print switch in the **Check & Describe** step there's no way to actually apply any of the **Check & Describe** settings to the print version explicitly after the split has happened. This is a bug/issue that we should address and I've created a ticket on it. For this particular chart I was able to make the necessary correction to the chart metadata such that the $ is also present in print mode.

**Comment by palewire** [comment]
This appears to be fixed, as demonstrated by [this example](https://app.datawrapper.de/chart/RJvc8/visualize?mode=print).

![Screenshot from 2020-01-09 09-54-08](https://user-images.githubusercontent.com/9993/72091870-052d7500-32c6-11ea-8474-5f2723434993.png)
