### ISSUE TITLE
Chart configuration reverts and things get weird when clicking different export options

### ISSUE THREAD

**Issue by LElebee** [datadesk/datawrapper-migration#66]
This issue results in the chart reverting to a previous unedited version of the chart. On export selection, the WEB style changes to PRINT and the latest edits do not stay in place. See this test example: https://app.datawrapper.de/chart/9jv29/visualize#design

![chart-reverts-to-earlier version](https://user-images.githubusercontent.com/17730643/71697260-55f41980-2d6c-11ea-93d0-5f6f658defaf.gif)

**Comment by palewire** [comment]
We've received numerous similar reports from our test users.

I suspect there is a flop in configuration settings when you click between web and print modes -- and that it's not making sense with our users. I see this sibling as linked in that way with #37.

I don't pretend to have the perfect solution, but it seems to me that user interface that controls the toggle between web and print needs a little streamlining.

**Comment by elanals** [comment]
Seems like this is general confusion about the way that the web/print switch works. The switch is there to allow different settings to be applied to a chart that has the same source data, depending on the context it will be used in. The settings for the two modes are in sync until the first time one clicks on the print switch. Unfortunately though it's all too easy to switch to print mode at some point while working on the chart, without realising/thinking about the fact that this creates a fork in the chart. From then on any settings applied will only be applied in the currently active mode. The user then typically continues working on the web version and totally forgets that the print one is getting left behind at an old state in this process. 

Agree that this is a workflow that could certainly do with some streamlining and thinking through in terms of the intuitiveness and usability. For example by adding a way of previewing the print version without actually forking.

For the meantime though - if you do think hiding the layout selection in the Design tab would help a la [#37](https://github.com/datadesk/datawrapper-migration/issues/37), we do have the possibility to do that now. I can also see what can be done to at the very least add a little explainer/warning bubble in the interface so that a user doesn't forget the fact that their chart is forked.

**Comment by palewire** [comment]
Yes. I agree to me there are two separate things, which we've already touched on here:

1) Users do not understand that when you switch to print mode while editing that it forks the metadata. I don't know the exact answer to solving this UI confusion but I think there needs to be some stronger link between the form and that button.

2) Users do not understand the distinction between the "mode" button on the editor and the theme pulldown menu in the design tab. This problem might not exist for other users, who do not have such a strict web/print split as we do. But I'm seeing it routinely here. For that reason, @elanals, *yes*, I would like the Design tab to be hidden if possible.
