### ISSUE TITLE
Color scheme on highlighted column charts is too light

### ISSUE THREAD

**Issue by palewire** [datadesk/datawrapper-migration#70]
We love the highlight option on the column chart. We want to use it a lot. One problem: The color scheme it adopts is too light for us to run in print. And we'd like it to be a little louder online too.

Here's what the current theme does for print.

![Screenshot from 2020-01-05 18-31-03](https://user-images.githubusercontent.com/9993/71791357-8e545b80-2fe9-11ea-8125-f074a896258c.png)

In that configuration, the highlighted color is `rgb(130, 198, 223)` and the default color is `#d3ebf4`. We'd like the unselected bars to be `rgb(130, 198, 223)` and for the selected column to be a bolder `#1281aa`.

Here's a [direct link](https://app.datawrapper.de/chart/MFcVu/visualize?mode=print#refine-the-chart) to the chart above.

**Comment by palewire** [comment]
Here's what I see for [a similar chart](https://app.datawrapper.de/chart/dRdLY/visualize?mode=print#refine-the-chart) now.

![Screenshot from 2020-01-14 19-31-27](https://user-images.githubusercontent.com/9993/72402606-82148080-3704-11ea-976d-418735ef49ac.png)

**Comment by palewire** [comment]
When I run the inspector in my console I see the three following blues.

Lighter: `#d4ebf4` `rgb(212, 235, 244)`
Default: `#83c6e0` `rgb(131, 198, 224)`
Darker: `#569ab3` `rgb(86, 154, 179)`

In the bug report above, the middle color is default for all bars. When a bar is hovered on, the higlighted bar steps up to the darker variation.

But, and here's in the bug, when a bar is highlighted in the annotate tab it retains the default color while all of the other bars step down to the lighter variation. We do not want that. The lighter color is too faint to show up in our print newspaper.

Instead, when a bar is highlighted we would like it to step up to the darker variation above while all of the others retain the default color. Can this be done?

**Comment by elanals** [comment]
As you correctly noticed the highlighted bar stays the original color while the others get lighter automatically.

We don't currently have the option for the opposite (ie highlight changes, others stay the same) though we do currently have an additional theme option in development whereby a theme can define a specific highlight color that is applied to highlighted elements.

There is also already a feature that prevents the fading out of the non-highlighted bars when highlighting one (so there is no color differences, just bolding plus showing the value label of the highlighted bar)

If you like, an intermediate solution I can offer until the highlight color feature is added would be to configure the 'no fade' option for the non-highlighted elements, so that the colors wouldn't be too light for print, but the user would have to be responsible for actively setting the correct color for the highlighted bar.

Should I do that?

**Comment by palewire** [comment]
Yes, let's do that. Thank you.

**Comment by elanals** [comment]
Great, done!
