### ISSUE TITLE
Prepended symbols do not appear in annotations on highlighted bars. They should

### ISSUE THREAD

**Issue by palewire** [datadesk/datawrapper-migration#72]
We've prepended a dollar sign to a column in "Check & Describe" on [this chart](https://app.datawrapper.de/chart/dRdLY/describe).

![Screenshot from 2020-01-14 19-16-57](https://user-images.githubusercontent.com/9993/72402220-5e046f80-3703-11ea-9a70-45405783e9c3.png)

While it does appear in our y-axis labels, it is missing on the values placed above the highlighted bars. We would like the dollar signs to appear there as well.

![Screenshot from 2020-01-14 19-27-50](https://user-images.githubusercontent.com/9993/72402399-fd296700-3703-11ea-95e1-220470b4fe90.png)

**Comment by palewire** [comment]
The print version of this chart also demonstrates bug #70

**Comment by elanals** [comment]
Making the prepend/append not show up on the value labels in column charts has been an active decision due to the fact that the prepend/append feature is often used to provide a more descriptive unit label on the top tick of the axis. When the value labels are on, including this on every label wouldn't be desirable. Long term we're looking to disentangle these features, having dedicated ones for the unit label, and the value labels. However for the time being you should be able to get the effect above my removing the prepended $ in the check & describe step, and instead applying a custom number format in the visualize step like this:

![image](https://user-images.githubusercontent.com/19191012/72623230-09e8cd80-3945-11ea-8415-0d18066e8ee8.png)

![image](https://user-images.githubusercontent.com/19191012/72623246-140acc00-3945-11ea-8b52-7912d0c4fc4e.png)

Currency and % symbols that come from the number format applied in the visualize step are by default shown on every tick, however this can be configured (in your themes) to only show up for the top tick. Would you prefer that?

**Comment by palewire** [comment]
Okay. Thank you.
